### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Mogway28** [lewapek/sds-dust-sensors-arduino-library#12]
Trying compile an example queryReportingMode.ino  there is a lots of problems:
ex.
src/SdsDustSensorResults.h:62:12: error: 'Mode' is not a class or namespace
       case Mode::Active: return "Mode: active";
src/SdsDustSensorResults.h: In constructor 'WorkingStateResult::WorkingStateResult(const Status&, byte*)':

**Comment by lewapek** [comment]
Hi,
it seems like you don't have library compiled.
You should install the library first. Have a look at the Arduino IDE tutorial:
https://www.arduino.cc/en/guide/libraries
