### ISSUE TITLE
Compilation fails with SoftwareSerial.h not found. Library.json version doesn't match tag 1.4.0?

### ISSUE THREAD

**Issue by sankara** [lewapek/sds-dust-sensors-arduino-library#23]
When I try to install this library using the library manager, it fails saying "SoftwareSerial.h" is not found. I looked into the codebase and I clearly see that you have #ifndef statements to validate if SoftwareSerial is required before including it. So I opened up the downloaded code and found that it was different from what I saw on Github. I was able to workaround the issue then by manually downloading the codebase and installing it as zip. 

I did further research and found you have specified the library version as 1.3.2 in library.json whereas the changes that has the #ifndef statements were made after v1.3.2 tag was released. The latest tag seems to be 1.4.0. I'll follow this up with a PR to change the library version (assuming my diagnosis is correct).

**Comment by sankara** [comment]
Here's the PR: #24

**Comment by lewapek** [comment]
PR merged
Thanks!

**Comment by sankara** [comment]
@lewapek You may have to create a new tag/release for the indexer to pick it up.

**Comment by lewapek** [comment]
You're right
There is now 1.4.1 tag and release with proper versions included
https://github.com/lewapek/sds-dust-sensors-arduino-library/releases/tag/1.4.1
