### ISSUE TITLE
Examples have reversed arguments

### ISSUE THREAD

**Issue by lenaxia** [lewapek/sds-dust-sensors-arduino-library#26]
Exmaples have sds(rxPin, txPin), however this results in an error. I had to set it as sds(txPin, rxPin) for mine to work.

**Comment by lewapek** [comment]
Hi,
you probably need to switch rx and tx connections on the board. The library just passes rx and tx (in that order) to `SoftwareSerial` constructor:
https://github.com/lewapek/sds-dust-sensors-arduino-library/blob/master/src/Serials.h#L56
