### ISSUE TITLE
sds011 stuck in custom mode

### ISSUE THREAD

**Issue by msnoeyink** [lewapek/sds-dust-sensors-arduino-library#31]
Hey, i tried the custom timing mode and now the sensor kind of seems like its stuck in it. Ofc i tried to upload other programs like the quickstart but the behaviour of the sensor doesnt change, furthermore there are quite many reading errors.

**Comment by lewapek** [comment]
Hey,
looks like this one is quite old. Without further info it's difficult to say why that happened. Could be the faulty sensor itself too
