### ISSUE TITLE
Error on linking: undefined reference to `vtable for Serials::AbstractSerial'

### ISSUE THREAD

**Issue by michelep** [lewapek/sds-dust-sensors-arduino-library#8]
ino.cpp.o:(.text._ZN7Serials16InternalSoftwareD2Ev[Serials::InternalSoftware::~InternalSoftware()]+0x0): undefined reference to `vtable for Serials::AbstractSerial'
collect2: error: ld returned 1 exit status

**Comment by lewapek** [comment]
Which version do you use? Can you provide more info - paste your sketch here?
I'm currently using 1.3.0 in one of my projects and it works fine. You can try that (1.3.0) for now

**Comment by michelep** [comment]
Version of what ?

**Comment by lewapek** [comment]
"Nova Fitness Sds dust sensors library" version

**Comment by lewapek** [comment]
https://github.com/lewapek/sds-dust-sensors-arduino-library/releases

**Comment by lewapek** [comment]
@michelep 
https://github.com/lewapek/sds-dust-sensors-arduino-library/pull/9 should solve the problem also on master branch
